title: Prithyu Gurunath
description: This site is about Prithyu Gurunath.
email: your-email@domain.com
# social links
github_username:  pgurunathh

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
