title: All About Prithyu Gurunath
author: Prithyu Gurunath
email: your-email@domain.com
description: > This site is about Prithyu Gurunath.
# social links
twitter_username: prithyu
github_username:  pgurunathh

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
